sitio:
    resource: "@SitioBundle/Resources/config/routing.yml"
    prefix:   /

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /

pagina_estatica:
    path: /sitio/{pagina}/
    defaults: {_controller: SitioBundle:Default:estatica}

portada:
    path: /{ciudad}
    defaults: {_controller: SitioBundle:Default:portada}

#definición de una redirección

_portada:
    path: /
    defaults: {_controller: FrameworkBundle:Redirect:redirect, route: portada, ciudad: '%cupon.ciudad_por_defecto%'}